### PR TITLE
Add Corppass helper

### PR DESCRIPTION
**Pull request by snghanjie**
This PR adds the CorpPass helper into the library.

_**Note: Will update once this is tested as we have not onboarded SPCP yet**_

### CODE REVIEW

**Comment by LoneRifle** [comment]
Thought to ask about the status of this. We will be moving to OIDC for both SingPass and CorpPass in due course, and would benefit from having a single library deal with both.

Thanks for the work done here!

**Comment by dyihoon90** [comment]
hi @snghanjie, just checking in on how your team is doing with Corppass and whether we can update the status. Thanks!

**Comment by randName** [comment]
our team will complete onboarding of SP/CP soon (within a month) and I have rebased the upstream changes in my fork ( https://github.com/randName/singpass-myinfo-oidc-helper/ ) to make sure the patches here still work.

I would just like to check the version of `node` and `npm` used by the maintainers as the lockfile version is still 1. Thanks!

**Comment by snghanjie** [comment]
I realised that my project will not be able to properly verify this as we need to integrate with this [new flow](https://stg-id.singpass.gov.sg/docs/authorization/api). I think the code here should most likely work since it's almost the same as the Singpass version. I have been testing with [Mockpass](https://github.com/opengovsg/mockpass) and it has worked with that so far.

**Review by Gyunikuchan — APPROVED** [review]

**Comment by Gyunikuchan** [comment]
> our team will complete onboarding of SP/CP soon (within a month) and I have rebased the upstream changes in my fork ( https://github.com/randName/singpass-myinfo-oidc-helper/ ) to make sure the patches here still work.
> 
> I would just like to check the version of `node` and `npm` used by the maintainers as the lockfile version is still 1. Thanks!

This lib is still built on node v12.22.5 and npm v6.14.14
We should be completing our move to node 16 and npm 8 later this year, which should be using lockfile v2
Do you have any concerns on this? (i.e. upgrading too fast or too slow?)

**Comment by randName** [comment]
no concerns since this has been merged already, but it would be good to indicate them somewhere for reference

**Pull request merged**
